name:                icfpc2020
version:             0.1.0.0
github:              "nobsun/icfpc2020"
license:             BSD3
author:              "Nobuo Yamashita"
maintainer:          "nobsun@sampou.org"
copyright:           "Copyright: (c) 2020 Nobuo Yamashita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/icfpc2020#readme>

dependencies:
- base >= 4.7 && < 5
ghc-options:
- -Wall

library:
  dependencies:
  - containers
  source-dirs: src

executables:
  icfpc2020:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2020

  solution:
    main:                solution.hs
    other-modules:
    - CurlCmd
    source-dirs:         app-solution
    ghc-options:
    - -rtsopts
    - -static
    - -threaded
    cc-options: -static
    ld-options:
    - -static
    - -pthread
    dependencies:
    - icfpc2020
    - process

  # libcurl からリンクされている krb5 ライブラリの
  # *.a イメージが Debian では提供されていなかったので
  # static link できなかった
  solution-dyn:
    main:                solution-dyn.hs
    other-modules:
    - CurlLib
    - CurlCmd
    source-dirs:         app-solution
    ghc-options:
    - -rtsopts
    - -static
    - -threaded
    dependencies:
    - icfpc2020
    - process
    - curl

tests:
  icfpc2020-test:
    main:                spec.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2020
